### ISSUE TITLE
Comments should be larger than one line on main.php

### ISSUE THREAD

**Issue by joevegan** [joevegan/ticketdesk#3]

**Comment by Kamori** [comment]
https://github.com/joevegan/ticketdesk/pull/13

This might need some further work. Notably the recent tickets section. But this issue should be good.

**Comment by joevegan** [comment]
Code looks good will test tomorrow and close it out once tested

**Comment by Kamori** [comment]
So one thing to consider that may help. IMO tickets should also have a subject line separate from comments. Recent tickets would then be the subject line and not the comments.

**Comment by joevegan** [comment]
Hmm, I feel like the category/subcategory fields should define "subject". That way reporting would be on standardized categories vs free form subject.

Perhaps we add those to the recent tickets?

Maybe ticket type too. (Request,issue, outage)

Thoughts?

**Comment by Kamori** [comment]
So to me a subject gives a little bit different definition to the issue sort of a short description to the issue.

For example depending on the customer of your application say they were creating tickets for customers of their minecraft server hosting company. You could get 2 very different tickets

1.) He can't connect to his servers ip and port
2.) Refund request


In this scenario and with the idea of data reports in the future. You could layout the application  to say

Subject: Refund Request planetcraftservers
Category: Account Management
Sub Category: Refund Request

With this people can quickly tell this is for the account planetcraftservers and get the details about it being a Refund Request in the subject + in the sub-category for later reports.

However, this is just a thought.

Moving on, yes I agree that the categories should be shown instead of the comments simply due to the type of data that may be present could be variable in length/style. If you wanted to keep the comments, I would recommend moving it to its own page or something so its not a small side panel.

Down for any more ideas you have.

**Comment by joevegan** [comment]
Lets add subject, and update the recent tickets to show subject and category/subcategory.

The comments is more the original "request details". If you click the status button next to a recent ticket it will take you to a view ticket screen where you can see and edit the ticket adding more notes as needed so they can always go there to view the full request details and/or work on the ticket.

I planned to add another panel that would auto populate once the client id is typed in with the tickets for that client--what do you think about that? Maybe below those two panels?

**Comment by joevegan** [comment]
hey i put the latest build here: http://devmonkeyz.com/ticketdev/ it has
your pr's in it. As well the subject line addition, i updated the db schema
for it too.

Good working with you! :D

**Comment by joevegan** [comment]
This issue corrected with Kamori's pr #13
